# Generated by Django 4.2 on 2025-03-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_delete_post_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
